name = "MathAccessories"
uuid = "2bbdb101-8967-472a-930f-60e813a9a11d"
authors = ["Rodrigo Muniz <rodrigosilvamuniz@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
